services:
  - type: web
    name: winflow-api
    runtime: docker
    rootDir: winflow/winflow
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: winflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: winflow-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: winflow-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: winflow-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: winflow-db
          property: password
      - key: ODDS_API_KEY
        sync: false

databases:
  - name: winflow-db
    plan: free
