# --- EXTERNAL API CONFIGURATION ---
odds.api.key=${ODDS_API_KEY}
odds.api.url=https://api.the-odds-api.com/v4/sports/

# --- POSTGRESQL DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://localhost:5432/winflow
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE (JPA) SETTINGS ---
# "update" tells Spring: "If the tables don't exist, create them. If they do exist, leave the data alone!"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true